group-role_index:
    path:     /
    defaults: { _controller: "DoCarmoAppBundle:GroupRole:index" }
    methods:  GET

group-role_show:
    path:     /{id}/show
    defaults: { _controller: "DoCarmoAppBundle:GroupRole:show" }
    methods:  GET

group-role_new:
    path:     /new
    defaults: { _controller: "DoCarmoAppBundle:GroupRole:new" }
    methods:  [GET, POST]

group-role_edit:
    path:     /{id}/edit
    defaults: { _controller: "DoCarmoAppBundle:GroupRole:edit" }
    methods:  [GET, POST]

group-role_delete:
    path:     /{id}/delete
    defaults: { _controller: "DoCarmoAppBundle:GroupRole:delete" }
    methods:  DELETE
