group-profile_index:
    path:     /
    defaults: { _controller: "DoCarmoAppBundle:GroupProfile:index" }
    methods:  GET

group-profile_show:
    path:     /{id}/show
    defaults: { _controller: "DoCarmoAppBundle:GroupProfile:show" }
    methods:  GET

group-profile_new:
    path:     /new
    defaults: { _controller: "DoCarmoAppBundle:GroupProfile:new" }
    methods:  [GET, POST]

group-profile_edit:
    path:     /{id}/edit
    defaults: { _controller: "DoCarmoAppBundle:GroupProfile:edit" }
    methods:  [GET, POST]

group-profile_delete:
    path:     /{id}/delete
    defaults: { _controller: "DoCarmoAppBundle:GroupProfile:delete" }
    methods:  DELETE
