<?php

namespace DoCarmo\AppBundle\Repository;

/**
 * GroupRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
