<?php

namespace DoCarmo\AppBundle\Repository;

/**
 * GroupProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupProfileRepository extends \Doctrine\ORM\EntityRepository
{
}
