<?php

namespace DoCarmo\AppBundle\Repository;

/**
 * SystemRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
